### PR TITLE
Swati/nullifier updates

### PR DESCRIPTION
**Pull request by SwatiEY**

### CODE REVIEW

**Comment by jimthematrix** [comment]
@SwatiEY can you re-submit the PR against the `refactor` branch instead?

**Review by jimthematrix — CHANGES_REQUESTED** [review]
when I tested the update locally, I ran into this error when trying to deposit:

```
Revert reason: The proof has not been verified by the contract
```

From preliminary investigation the error is from the `verificationCalculation()` step. Looks like the proving keys need to be updated too (only the verifiying keys are updated)?

**Comment by SwatiEY** [comment]
Can you please run ./bin/setup before running the tests. This will update the proving and verification keys for the updated circuits.

**Review by jimthematrix — APPROVED** [review]
I've successfully tested the updated contract code. After re-running the set up, I was able to go through the mint-deposit-withdraw-transfer-withdraw flows between two instances of the zapp stack. Thanks @SwatiEY for making the fix!

**Pull request merged**
